INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (9, N'莫燕萍', N'财务处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (10, N'熊小倩', N'财务处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (11, N'义清泉', N'财务处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (12, N'林枝杭', N'财务处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (13, N'柯凌奕', N'财务处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (14, N'周昕昀', N'财务处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (15, N'李欢欢', N'财务处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (16, N'陈芳莲', N'财务处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (17, N'杨林', N'党政办公室'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (18, N'侯芳', N'党政办公室'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (19, N'廖蓉', N'党政办公室'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (20, N'石玉湘', N'党政办公室'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (21, N'唐春', N'党政办公室'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (22, N'覃思斯', N'党政办公室'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (23, N'吴昊', N'党政办公室'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (24, N'王旭', N'党政办公室'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (25, N'邱东海', N'党政办公室'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (26, N'陈玲', N'质量与规划办公室'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (27, N'吴保红', N'质量与规划办公室'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (28, N'张剑曦', N'质量与规划办公室'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (29, N'石文', N'质量与规划办公室'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (30, N'黄欣萍', N'组织人事处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (31, N'董海丽', N'组织人事处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (32, N'张丽梅', N'组织人事处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (33, N'张妮', N'组织人事处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (34, N'王伟杰', N'组织人事处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (35, N'武淑辉', N'组织人事处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (36, N'孙苑雯', N'组织人事处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (37, N'班仲明', N'组织人事处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (38, N'姚瑶', N'党政办公室'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (39, N'唐欣', N'组织人事处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (40, N'张杰', N'教务与实训管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (41, N'韦峥宇', N'教务与实训管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (42, N'李柳芳', N'教务与实训管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (43, N'温永斌', N'教务与实训管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (44, N'钟雪勤', N'教务与实训管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (45, N'王宇翾', N'教务与实训管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (46, N'韦群', N'教务与实训管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (47, N'梁海荣', N'教务与实训管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (48, N'张贤茂', N'教务与实训管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (49, N'肖榕', N'教务与实训管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (50, N'颜晨晨', N'教务与实训管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (51, N'徐毅华', N'科研处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (52, N'刘继凤', N'科研处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (53, N'黄心宁', N'科研处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (54, N'陈超', N'信息中心'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (55, N'古宝雄', N'信息中心'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (56, N'覃绍启', N'信息中心'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (57, N'黎航', N'信息中心'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (58, N'王明勤', N'信息中心'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (59, N'荣国富', N'信息中心'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (60, N'岑祥宁', N'信息中心'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (61, N'谭成芝', N'招生就业办公室'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (62, N'邓嘉', N'招生就业办公室'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (63, N'汤淇', N'招生就业办公室'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (64, N'覃铸军', N'招生就业办公室'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (65, N'姚甜', N'招生就业办公室'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (66, N'卢思言', N'招生就业办公室'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (67, N'唐日兴', N'学生工作处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (68, N'蒙恬', N'学生工作处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (69, N'廖州萍', N'学生工作处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (70, N'吴春芳', N'学生工作处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (71, N'陈新蓉', N'学生工作处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (72, N'李妮', N'学生工作处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (73, N'黄黎黎', N'学生工作处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (74, N'石文静', N'学生工作处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (75, N'罗贵月', N'学生工作处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (76, N'杨雨薇', N'学生工作处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (77, N'周映宏', N'学生工作处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (78, N'唐琪', N'学生工作处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (79, N'胡雅宁', N'学生工作处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (80, N'余萍萍', N'团委'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (81, N'陈楚钘', N'团委'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (82, N'任春鹏', N'团委'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (83, N'杨国成', N'安全保卫处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (84, N'惠晓萌', N'安全保卫处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (85, N'方芳', N'安全保卫处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (86, N'廖俊', N'安全保卫处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (87, N'刘翔', N'安全保卫处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (88, N'林桂文', N'继续教育处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (89, N'袁光明', N'继续教育处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (90, N'杨康妮', N'继续教育处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (91, N'覃晴', N'继续教育处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (92, N'林洋洋', N'继续教育处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (93, N'叶丰', N'后勤与资产管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (94, N'周明', N'后勤与资产管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (95, N'何基通', N'后勤与资产管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (96, N'陈婷', N'后勤与资产管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (97, N'梁智', N'后勤与资产管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (98, N'黄巍', N'后勤与资产管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (99, N'石善辉', N'后勤与资产管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (100, N'刘秀美', N'后勤与资产管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (101, N'黎莹莹', N'后勤与资产管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (102, N'陈晋元', N'后勤与资产管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (103, N'龙丹萍', N'后勤与资产管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (104, N'韦金利', N'后勤与资产管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (105, N'黄桂昭', N'后勤与资产管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (106, N'陈东兰', N'后勤与资产管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (107, N'覃招达', N'后勤与资产管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (108, N'唐达宏', N'后勤与资产管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (109, N'莫奋', N'后勤与资产管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (110, N'覃华', N'后勤与资产管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (111, N'曾秀宁', N'后勤与资产管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (112, N'曾秀娟', N'后勤与资产管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (113, N'曾秀华', N'后勤与资产管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (114, N'覃庆康', N'后勤与资产管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (115, N'曹甜珍', N'后勤与资产管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (116, N'梁凤彬', N'后勤与资产管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (117, N'张凤秀', N'后勤与资产管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (118, N'石才领', N'后勤与资产管理处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (119, N'李丽芬', N'纪检监察室'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (120, N'马玉芸', N'纪检监察室'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (121, N'吕涛', N'宣传策划处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (122, N'蒋晨曦', N'宣传策划处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (123, N'朱秀', N'宣传策划处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (124, N'潘兴翼', N'宣传策划处'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (125, N'梁柳青', N'大专部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (126, N'何煜', N'大专部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (127, N'吴红梅', N'大专部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (128, N'赵丹', N'大专部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (129, N'吴冰', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (130, N'莫敏', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (131, N'苏娜', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (132, N'孙临风', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (133, N'彭莉', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (134, N'李珊珊', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (135, N'李华', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (136, N'黄巧芳', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (137, N'唐慧', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (138, N'梁洁', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (139, N'曹兴旺', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (140, N'蒋海贤', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (141, N'梁丽娜', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (142, N'黄莺', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (143, N'曾奕', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (144, N'周靖杰', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (145, N'彭葆慧', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (146, N'陈红', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (147, N'闭青', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (148, N'彭卉', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (149, N'韦俐玲', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (150, N'潘钟萍', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (151, N'曾绍彬', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (152, N'马燕兰', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (153, N'肖曼萍', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (154, N'高凡', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (155, N'郭婉滢', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (156, N'覃银纤', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (157, N'邹智勇', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (158, N'邱红文', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (159, N'蒋柳佺', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (160, N'秦仲岳', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (161, N'黄炜', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (162, N'唐满燕', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (163, N'黄晓萍', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (164, N'石军', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (165, N'谭柳军', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (166, N'朱晓菊', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (167, N'赖世峰', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (168, N'陈璐璐', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (169, N'张慧云', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (170, N'覃燕', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (171, N'韩煜章', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (172, N'梁田', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (173, N'朱月清', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (174, N'骆佳玥', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (175, N'覃会锋', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (176, N'黄雯婷', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (177, N'蒙艺文', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (178, N'覃显业', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (179, N'罗彩云', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (180, N'朱紫绮', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (181, N'李庆玲', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (182, N'肖荣凡', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (183, N'林丽', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (184, N'胡乙丹', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (185, N'唐晨', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (186, N'李斌', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (187, N'陈晓', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (188, N'丁琼', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (189, N'梁倩晓', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (190, N'覃剑萍', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (191, N'柴晓霞', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (192, N'杨丽波', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (193, N'刘焕林', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (194, N'林钰芝', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (195, N'丁凯婷', N'公共基础部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (196, N'于载欣', N'体育教学部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (197, N'姜明浩', N'体育教学部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (198, N'董明兴', N'体育教学部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (199, N'刘荣明', N'体育教学部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (200, N'罗佳娜', N'体育教学部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (201, N'王巍', N'体育教学部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (202, N'磨练', N'体育教学部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (203, N'陈安乐', N'体育教学部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (204, N'杨立文', N'体育教学部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (205, N'阳耀玲', N'体育教学部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (206, N'李芃伶', N'体育教学部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (207, N'杨日锋', N'体育教学部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (208, N'覃叶颖', N'体育教学部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (209, N'刘新明', N'体育教学部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (210, N'罗佳丽', N'体育教学部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (211, N'孙文军', N'体育教学部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (212, N'谭云', N'体育教学部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (213, N'韦方杰', N'体育教学部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (214, N'蒋芬', N'体育教学部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (215, N'伍泓宇', N'体育教学部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (216, N'韦园园', N'体育教学部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (217, N'韦福慧', N'体育教学部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (218, N'蒙冠名', N'体育教学部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (219, N'朱媚', N'体育教学部'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (220, N'陆珈璐', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (221, N'赵永霞', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (222, N'陈君', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (223, N'薛文灵', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (224, N'刘玉洁', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (225, N'卢友彩', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (226, N'黎耀', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (227, N'吴选花', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (228, N'陈相才', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (229, N'梁欣', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (230, N'云青', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (231, N'邓祺', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (232, N'李航', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (233, N'贾颖颖', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (234, N'刘霞', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (235, N'李凯', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (236, N'杨柳姿', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (237, N'赵晓艳', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (238, N'马振文', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (239, N'卢海枚', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (240, N'莫乾勋', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (241, N'林兰鹃', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (242, N'陈立昌', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (243, N'钟子然', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (244, N'郑旭舒', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (245, N'徐健', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (246, N'黄勇慧', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (247, N'曹红香', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (248, N'覃海思', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (249, N'谢文宗', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (250, N'丁建斌', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (251, N'李晓波', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (252, N'邓春丽', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (253, N'李永涛', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (254, N'李颖琦', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (255, N'韦冰', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (256, N'张丽英', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (257, N'朱经辉', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (258, N'马启忠', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (259, N'覃雪耿', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (260, N'赵精华', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (261, N'罗丽姣', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (262, N'廖晓静', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (263, N'丁淋淋', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (264, N'张淋稀', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (265, N'韦浪涛', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (266, N'梁辰', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (267, N'何日明', N'工程机械系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (268, N'韦江彬', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (269, N'吴地固', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (270, N'陆率帅', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (271, N'蒋恒馥', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (272, N'李静', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (273, N'蒋国昕', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (274, N'江丽妍', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (275, N'黄惠', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (276, N'黄丽娟', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (277, N'卢柳梅', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (278, N'覃筱芸', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (279, N'冯兰斯', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (280, N'江拥军', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (281, N'韦弢勇', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (282, N'彭媛媛', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (283, N'陈明莉', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (284, N'钟海涛', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (285, N'韦成', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (286, N'梁雪莉', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (287, N'谢承乐', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (288, N'李明江', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (289, N'梁启忠', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (290, N'何述鹏', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (291, N'邵剑钊', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (292, N'廖武瑾', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (293, N'阮武启', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (294, N'李庆阳', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (295, N'李星潮', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (296, N'冯春', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (297, N'蔡旭彪', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (298, N'吴佳璐', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (299, N'张宏华', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (300, N'雷少学', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (301, N'杨媚', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (302, N'李柱荣', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (303, N'莫雪环', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (304, N'韦焱文', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (305, N'廖霞', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (306, N'张全', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (307, N'黄彦博', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (308, N'李秀练', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (309, N'卢羽婷', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (310, N'李兰', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (311, N'张兴富', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (312, N'钟玲', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (313, N'蒋慧敏', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (314, N'潘红洁', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (315, N'王兴仁', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (316, N'林敬庭', N'交通运输系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (317, N'李艳华', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (318, N'张嘉嘉', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (319, N'刘玉琴', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (320, N'杜桓宇', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (321, N'黄军强', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (322, N'黄永斌', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (323, N'吴春荣', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (324, N'冯鑫', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (325, N'徐鸿琳', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (326, N'刘林凤', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (327, N'袁婧', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (328, N'李阳', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (329, N'马彩金', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (330, N'潘晓丹', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (331, N'史芳伶', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (332, N'张莉萍', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (333, N'滕怡宁', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (334, N'王少君', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (335, N'朱承丹', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (336, N'张珺', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (337, N'黄维玲', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (338, N'黄春柳', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (339, N'李婷', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (340, N'黎明玥', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (341, N'张宇', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (342, N'慎阳', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (343, N'王华程', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (344, N'黄梅宇', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (345, N'陈湘怡', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (346, N'温岚兰', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (347, N'曾春', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (348, N'唐雪', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (349, N'曾夏', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (350, N'阳洪涛', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (351, N'蒋利芳', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (352, N'陈茜', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (353, N'陈博宁', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (354, N'李雨徽', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (355, N'熊运', N'经济贸易系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (356, N'经本明', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (357, N'兰丽丽', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (358, N'蒋科', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (359, N'余虹', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (360, N'张慧', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (361, N'罗俊', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (362, N'章进', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (363, N'赵子熠', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (364, N'吴卫兵', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (365, N'袁慧', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (366, N'伍孙强', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (367, N'谢宇斯', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (368, N'刘娴', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (369, N'李小鹃', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (370, N'朱盈燕', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (371, N'余冰', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (372, N'陈权', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (373, N'杨永隆', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (374, N'秦意', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (375, N'李梦莹', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (376, N'谭洁芸', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (377, N'杨颂庆', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (378, N'杨芙蓉', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (379, N'刘婧', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (380, N'罗媛媛', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (381, N'黄克坚', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (382, N'覃平业', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (383, N'于靖晖', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (384, N'罗丹阳', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (385, N'何艳菊', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (386, N'欧阳丽君', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (387, N'陈欢欢', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (388, N'黄菲菲', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (389, N'韦兰甜', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (390, N'刘丽', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (391, N'李海兰', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (392, N'蒙俏妮', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (393, N'卢泓伊', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (394, N'黄迪', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (395, N'张菁', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (396, N'韦浪云', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (397, N'李瞻', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (398, N'蓝鹏', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (399, N'罗茜', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (400, N'陈璨', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (401, N'贾晓兰', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (402, N'韦翼峰', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (403, N'郭子薇', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (404, N'黄丽程', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (405, N'葵莉', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (406, N'谢伟媚', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (407, N'林姿', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (408, N'刘荔贞', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (409, N'刘小环', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (410, N'覃谧', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (411, N'韦俊旭', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (412, N'黄琪', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (413, N'韦姚佳', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (414, N'覃世琳', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (415, N'王厦', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (416, N'余林倩', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (417, N'文伊', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (418, N'阮佳佳', N'文化旅游系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (419, N'伍依安', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (420, N'涂俊', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (421, N'李海辉', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (422, N'黄宇飞', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (423, N'兰伟华', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (424, N'曹致强', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (425, N'陶静', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (426, N'黄国燕', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (427, N'卢星', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (428, N'赵赤辉', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (429, N'宁方方', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (430, N'覃素华', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (431, N'周凌', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (432, N'金明霞', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (433, N'赵玲', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (434, N'韦晓高', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (435, N'蔡凌燕', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (436, N'黄御金', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (437, N'周秀妹', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (438, N'林柳波', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (439, N'谢建强', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (440, N'蒋钰', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (441, N'韩晶', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (442, N'陈颖', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (443, N'张煜琦', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (444, N'张楼英', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (445, N'钟严毅', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (446, N'李璐', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (447, N'秦怡婷', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (448, N'徐娟', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (449, N'彭耀春', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (450, N'肖卫', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (451, N'张展开', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (452, N'陈彦求', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (453, N'陈曼琦', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (454, N'龙媛', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (455, N'郑烁', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (456, N'秦菊梅', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (457, N'覃丽霞', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (458, N'朱梦迪', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (459, N'蓝利桃', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (460, N'梁双慧', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (461, N'龙英美', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (462, N'兰岚', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (463, N'张叶昕', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (464, N'苏月玲', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (465, N'黄宝丽', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (466, N'邓小艳', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (467, N'黄柳琴', N'艺术设计系'); GO
INSERT INTO [Teacher]([SerialNumber], [Name], [Department]) VALUES (468, N'陈美娟', N'艺术设计系'); GO
